version: '3.1'
services:
    hello:
        image: hello-ee:1
        restart: always
        environment:
            JAVA_TOOL_OPTIONS: '-Xmx64m'
        ports:
            - 8080
        networks:
            - webnet
    home:
        image: home-ee:1
        restart: always
        environment:
            JAVA_TOOL_OPTIONS: '-Xmx64m'
        ports:
            - 8080
        networks:
            - webnet
    lb:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - home
            - hello
        ports:
            - "4000:4000"
        networks:
            - webnet
networks:
    webnet:
